version: '3.8'

services:
  ai-service:
    build: .
    container_name: planbook-ai-service
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped
