version: "3.8"

services:
  # Redis Service
  redis:
    image: redis:7-alpine
    container_name: planbook-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  # MongoDB Service
  mongodb:
    image: mongo:7
    container_name: planbook-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: planbook_db
    restart: unless-stopped

  # FastAPI Service
  ai-service:
    build: .
    container_name: planbook-ai-service
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - mongodb
    restart: unless-stopped

  # Celery Worker
  celery-worker:
    build: .
    container_name: planbook-celery-worker
    command: celery -A app.workers.celery_app worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - mongodb
    restart: unless-stopped

  # Celery Flower (Monitoring)
  celery-flower:
    build: .
    container_name: planbook-celery-flower
    command: celery -A app.workers.celery_app flower --port=5555
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - celery-worker
    restart: unless-stopped

volumes:
  redis_data:
  mongodb_data:
